### ISSUE TITLE
how to rectify this error

### ISSUE THREAD

**Issue by nousath** [johnpryan/date_utils#14]
Because date_utils >=0.1.0 depends on intl ^0.15.0 and every version of flutter_localizations from sdk depends on intl 0.16.0, date_utils >=0.1.0 is incompatible with flutter_localizations from sdk.
So, because cargoos depends on both flutter_localizations any from sdk and date_utils ^0.1.0+2, version solving failed.
pub upgrade failed (1)

**Comment by josephmangmang** [comment]
Same here.

> Running "flutter pub get" in beprime...                         
Because every version of flutter_localizations from sdk depends on intl 0.16.0 and beprime depends on intl ^0.15.8, flutter_localizations from sdk is forbidden.

> So, because beprime depends on flutter_localizations any from sdk, version solving failed.

> pub get failed (1; So, because beprime depends on flutter_localizations any from sdk, version solving failed.)

**Comment by ly410726** [comment]
Because no versions of date_utils match >0.1.0+2 <0.2.0 and date_utils 0.1.0+2 depends on intl ^0.15.0, date_utils ^0.1.0+2 requires intl ^0.15.0.
And because every version of flutter_localizations from sdk depends on intl 0.16.0, date_utils ^0.1.0+2 is incompatible with flutter_localizations from sdk.
So, because flutter_agent depends on both flutter_localizations any from sdk and date_utils ^0.1.0+2, version solving failed.

**Comment by koraybicer** [comment]
I was able to resolve this issue by including date_utils.dart directly into project.

**Comment by johnpryan** [comment]
I'm about to publish `0.2.0`, which should be compatible with the latest version of `intl` and `flutter_localizations`. Please reopen if you're still seeing this.
